POST http://localhost:3001/api/blogs
content-type:application/json

{
  "title": "Testss",
  "author": "Testss",
  "url": "Testss",
  "likes": 24
}

###
GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/users 
content-type:application/json

{
  "username":"Test",
  "name":"Test",
  "password":"Test"
}